version: '4.11.1'
services:
  location-tracker:
    build: ./location-tracker
    container_name: location-tracker-c
    ports:
      - '3000:3000'
    volumes:
      - ./location-tracker:/app
      - /app/node_modules