FROM node:19-alpine as build

WORKDIR /app

COPY . .

RUN rm -rf it-jobs-world

WORKDIR /app/location-tracker

RUN npm install

CMD npm run build

FROM nginx:1.23.3

COPY ./location-tracker/nginx/nginx.conf /etc/nginx/nginx.conf

RUN true

COPY --from=build /app/location-tracker/dist /usr/share/nginx/html