FROM node:19-alpine as build

WORKDIR /app

COPY . .

WORKDIR /app/location-tracker

RUN npm ci --only=production && \
    npm install --save-dev typescript && \
    npm run build

FROM nginx:1.23.3

COPY --from=build /app/location-tracker/nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/location-tracker/dist /usr/share/nginx/html