name: Location tracker Build and Update Development Docker Image
on:
  push:
    branches:
      - develop
    paths:
      - 'location-tracker/**'
      - 'core-common/**'

jobs:
  build-and-update-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        docker build -t andinh0410/location-tracker:$GITHUB_SHA -f Dockerfile-location-tracker .
    - name: Login to dockerhub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Image
      run: |
        docker push andinh0410/location-tracker:$GITHUB_SHA
